query GetCasesByNameIds($ids: [ID]) {
  cases(
    filters: { case_names: { id: { in: $ids } } }
    pagination: { limit: 70 }
  ) {
    data {
      id
      attributes {
        ...CaseFragment
      }
    }
  }
}
