query GetServiceCollectionById($id: ID) {
  serviceCollection(id: $id) {
    data {
      id

      attributes {
        name

        description

        deadlines

        price

        Title {
          id
          title

          titles {
            id
            title
          }
        }

        Footer {
          ...FooterFragment
        }

        sliderCase {
          ...SliderFragment
        }
        banner {
          data {
            attributes {
              ...MediaFragment
            }
          }
        }
        textBlocks {
          ...TextBlocksFragment
        }
        video {
          data {
            attributes {
              ...MediaFragment
            }
          }
        }
      }
    }
  }
}
