query GetServiceCollectionById($id: ID) {
  serviceCollection(id: $id) {
    data {
      id

      attributes {
        name
        content {
          ... on ComponentServicesContentTextVariant {
            idBlock
            id
            title
            description
          }

          ... on ComponentServicesContentSingleImageBlock {
            idBlock
            id
            title
            description
            image {
              data {
                attributes {
                  ...MediaFragment
                }
              }
            }
          }
        }

        description

        deadlines

        price

        Title {
          id
          title

          titles {
            id
            title
            activeTitle
          }
        }

        sliderCase {
          ...SliderFragment
        }

        textBlocks {
          ...TextBlocksFragment
        }

        video {
          data {
            attributes {
              ...MediaFragment
            }
          }
        }

        contentBanner {
          data {
            attributes {
              ...BannerFragment
            }
          }
        }
      }
    }
  }
}
