query GetServiceById($id: ID) {
  services(filters: { serviceName: { id: { eq: $id } } }) {
    data {
      attributes {
        SliderCase {
          cases {
            data {
              id
              attributes {
                title
                info
                imageMain {
                  data {
                    attributes {
                      name
                      url
                      width
                      height
                    }
                  }
                }
                imageBig {
                  data {
                    attributes {
                      name
                      url
                      width
                      height
                    }
                  }
                }
              }
            }
          }
        }

        Services {
          id
          title
          description
          service_collections {
            data {
              id
              attributes {
                name
                description
                price
                textBlocks {
                  titlle
                  description
                  id
                }
                banner {
                  data {
                    attributes {
                      name
                      url
                    }
                  }
                }
                sliderCase {
                  id
                  cases {
                    data {
                      attributes {
                        title
                        info

                        imageBig {
                          data {
                            attributes {
                              name
                              url
                            }
                          }
                        }
                        imageMain {
                          data {
                            attributes {
                              name
                              url
                            }
                          }
                        }
                      }
                    }
                  }
                }
                video {
                  data {
                    attributes {
                      name
                      url
                    }
                  }
                }
              }
            }
          }
        }

        Footer {
          title
          img {
            data {
              attributes {
                ...MediaFragment
              }
            }
          }
        }

        title
        textBlocks {
          id
          titlle
          description
        }
        description
        serviceName {
          data {
            id
            attributes {
              name
            }
          }
        }

        banner {
          data {
            attributes {
              name
              url
            }
          }
        }
        video {
          data {
            attributes {
              name
              url
            }
          }
        }
      }
    }
  }
}
