query GetServiceById($id: ID) {
  services(filters: { serviceName: { id: { eq: $id } } }) {
    data {
      attributes {
        SliderCase {
          ...SliderFragment
        }

        Services {
          id

          service_collections {
            data {
              id

              attributes {
                serviceColorImageComponent {
                  color

                  imageService {
                    data {
                      attributes {
                        ...MediaFragment
                      }
                    }
                  }
                }
                name

                description

                price

                textBlocks {
                  ...TextBlocksFragment
                }

                sliderCase {
                  ...SliderFragment
                }

                video {
                  data {
                    attributes {
                      ...MediaFragment
                    }
                  }
                }
              }
            }
          }
        }

        title

        content {
          ... on ComponentServicesContentTextVariant {
            idBlock
            id
            title
            description
          }

          ... on ComponentServicesContentSingleImageBlock {
            idBlock
            id
            title
            description
            image {
              data {
                attributes {
                  ...MediaFragment
                }
              }
            }
          }
        }

        textBlocks {
          ...TextBlocksFragment
        }

        description

        serviceName {
          data {
            id
            attributes {
              name
            }
          }
        }

        video {
          data {
            attributes {
              ...MediaFragment
            }
          }
        }

        contentBanner {
          data {
            attributes {
              ...BannerFragment
            }
          }
        }
      }
    }
  }
}
