query GetServiceById($id: ID) {
  services(filters: { serviceName: { id: { eq: $id } } }) {
    data {
      attributes {
        SliderCase {
          ...SliderFragment
        }

        Services {
          id
          title
          description

          service_collections {
            data {
              id

              attributes {
                name

                description

                price

                textBlocks {
                  ...TextBlocksFragment
                }
                banner {
                  data {
                    attributes {
                      ...MediaFragment
                    }
                  }
                }
                sliderCase {
                  ...SliderFragment
                }

                video {
                  data {
                    attributes {
                      ...MediaFragment
                    }
                  }
                }
              }
            }
          }
        }

        title

        textBlocks {
          ...TextBlocksFragment
        }

        description

        serviceName {
          data {
            id
            attributes {
              name
            }
          }
        }

        banner {
          data {
            attributes {
              ...MediaFragment
            }
          }
        }
        video {
          data {
            attributes {
              ...MediaFragment
            }
          }
        }
      }
    }
  }
}
