fragment CaseFragment on Case {
  title
  info
  imageMain {
    data {
      attributes {
        ...MediaFragment
      }
    }
  }
  imageBig {
    data {
      attributes {
        ...MediaFragment
      }
    }
  }
}
