fragment CaseFragment on Case {
  title
  info
  imageMain {
    data {
      attributes {
        ...MediaFragment
      }
    }
  }
  imageBig {
    data {
      attributes {
        ...MediaFragment
      }
    }
  }

  imageMainMobile {
    data {
      attributes {
        ...MediaFragment
      }
    }
  }

  imageBigMobile {
    data {
      attributes {
        ...MediaFragment
      }
    }
  }

  case_names {
    data {
      attributes {
        name
      }
    }
  }
}
