query GetHomePage {
  homePage {
    data {
      attributes {
        title
        HomeBanner {
          IntroCard {
            class
            id
            title
            info
          }
        }

        bannerMobile {
          data {
            attributes {
              name
              url
            }
          }
        }

        formSend {
          title
          description
          number
          address
          email
        }

        Partners {
          title
          description
          icons {
            data {
              id
              attributes {
                name
                url
                width
                height
              }
            }
          }
        }

        cases {
          data {
            id
            attributes {
              title
              info
              imageBig {
                data {
                  attributes {
                    url
                  }
                }
              }
              imageMain {
                data {
                  attributes {
                    url
                  }
                }
              }
            }
          }
        }

        banner {
          data {
            attributes {
              name
              url
            }
          }
        }
      }
    }
  }
}
