query GetComplexPage {
  complexAccompany {
    data {
      attributes {
        title
        description

        complexBlocks {
          ...ComplexBlock
        }

        banner {
          data {
            attributes {
              ...MediaFragment
            }
          }
        }

        footer {
          ...FooterFragment
        }
      }
    }
  }
}
