query GetComplexPage {
  complexAccompany {
    data {
      attributes {
        title
        description

        complexBlocks {
          ...ComplexBlock
        }

        footer {
          ...FooterFragment
        }
      }
    }
  }
}
