query GetCaseById($id: ID) {
  case(id: $id) {
    data {
      attributes {
        Footer {
          ...FooterFragment
        }

        mobileName

        backround

        content {
          ... on ComponentImageBlocksOneImage {
            idBlock
            id
            image {
              data {
                attributes {
                  ...MediaFragment
                }
              }
            }
          }

          ... on ComponentImageBlocksGridImage {
            idBlock
            id
            selectStreech
            threeImage {
              data {
                attributes {
                  ...MediaFragment
                }
              }
            }
            twoImage {
              data {
                attributes {
                  ...MediaFragment
                }
              }
            }
            oneImage {
              data {
                attributes {
                  ...MediaFragment
                }
              }
            }
          }

          ... on ComponentImageBlocksDoubleImage {
            id
            idBlock
            imageTwo {
              data {
                attributes {
                  ...MediaFragment
                }
              }
            }
            imageOne {
              data {
                attributes {
                  ...MediaFragment
                }
              }
            }
          }

          ... on ComponentImageBlocksTextBlock {
            id
            idBlock
            title
            description
            desctopMaxWidth
            selectType
          }

          ... on ComponentImageBlocksDoubleTextBlocks {
            id
            idBlock
            oldTitle
            oldDescription
            newTitle
            newDescription

            oldLogo {
              data {
                attributes {
                  ...MediaFragment
                }
              }
            }

            newLogo {
              data {
                attributes {
                  ...MediaFragment
                }
              }
            }
          }
        }
      }
    }
  }
}
