query GetComplexById($id: ID) {
  complex(id: $id) {
    data {
      attributes {
        name

        footer {
          ...FooterFragment
        }

        includes_blocks {
          data {
            id
            attributes {
              title

              blockHover {
                id
                title
                text
                subTitle
                list
              }

              includesContent {
                id
                title
                content
              }
            }
          }
        }

        offer {
          id
          price
        }

        description
        deadlines

        banner {
          data {
            attributes {
              ...MediaFragment
            }
          }
        }
      }
    }
  }
}
