query GetHomePage {
  homePage {
    data {
      attributes {
        title

        HomeBanner {
          ...GetHomeBanner
        }

        cases {
          ...GetHomeCases
        }
      }
    }
  }
}
