query GetHomePage {
  homePage {
    data {
      attributes {
        cases {
          ...GetHomeCases
        }

        bannerMedia {
          data {
            attributes {
              ...MediaFragment
            }
          }
        }
      }
    }
  }
}
