query GetOffersPage {
  offersPage {
    data {
      attributes {
        title
        description

        offersBlock {
          ...OffersBlock
        }

        img {
          data {
            attributes {
              ...MediaFragment
            }
          }
        }

        banner {
          data {
            attributes {
              ...MediaFragment
            }
          }
        }

        footer {
          ...FooterFragment
        }
      }
    }
  }
}
