query GetPartners {
  ourPartners(sort: "id:asc", pagination: { limit: 150 }) {
    data {
      attributes {
        noFillImage {
          data {
            attributes {
              ...MediaFragment
            }
          }
        }

        fillImage {
          data {
            attributes {
              ...MediaFragment
            }
          }
        }

        title
      }
    }
  }
}
