query GetPortfolio($ids: [ID]) {
  portfolio {
    data {
      attributes {
        cases(
          filters: { case_names: { id: { in: $ids } } }
          pagination: { limit: 70 }
        ) {
          data {
            id
            attributes {
              ...CaseFragment
            }
          }
        }
      }
    }
  }
}
