query GetPortfolio {
  portfolio {
    data {
      attributes {
        cases {
          data {
            id
            attributes {
              ...CaseFragment
            }
          }
        }
      }
    }
  }
}
