query GetServicesNamesOffer {
  serviceNames(sort: "id:asc") {
    data {
      id
      attributes {
        name
        nameID

        offers {
          data {
            id
            attributes {
              ...OfferFragment
            }
          }
        }
      }
    }
  }
}
