query GetStudio {
  studio {
    data {
      attributes {
        title

        introCards {
          ...IntroCardFragment
        }

        vacancies {
          title
          description
          date
          info

          vacancies {
            id
            title
            descriptionVacancy
            level
            btnLink
            telegrammLink
          }

          image {
            data {
              attributes {
                ...MediaFragment
              }
            }
          }
        }

        aboutSection {
          id
          mainTitle
          description
          aboutTitle
          aboutDescription
        }

        video {
          data {
            attributes {
              ...MediaFragment
            }
          }
        }
      }
    }
  }
}
