query GetServicesPage {
  servicesPage {
    data {
      attributes {
        heading
        description
        servicesTitle
        servicesDescription

        textBlocks {
          id
          titlle
          description
        }

        video {
          data {
            attributes {
              name
              url
            }
          }
        }
      }
    }
  }
}
