query GetStudio {
  studio {
    data {
      attributes {
        title

        introCards {
          ...IntroCardFragment
        }

        vacancies {
          title
          description
          date
          info

          vacancies {
            data {
              id

              attributes {
                vacancy {
                  title
                  descriptionVacancy
                  selectLevel
                  btnLink
                  telegrammLink
                }
              }
            }
          }

          image {
            data {
              attributes {
                ...MediaFragment
              }
            }
          }
        }

        aboutSection {
          id
          mainTitle
          description
          aboutTitle
          aboutDescription
        }

        video {
          data {
            attributes {
              ...MediaFragment
            }
          }
        }

        videoMobile {
          data {
            attributes {
              ...MediaFragment
            }
          }
        }
      }
    }
  }
}
