query GetServicesNames {
  serviceNames {
    data {
      id
      attributes {
        name
        service {
          data {
            id
            attributes {
              title
            }
          }
        }
      }
    }
  }
}
