fragment GetHomePartners on ComponentSectionsPartners {
  title

  our_partners {
    data {
      attributes {
        noFillImage {
          data {
            attributes {
              ...MediaFragment
            }
          }
        }

        fillImage {
          data {
            attributes {
              ...MediaFragment
            }
          }
        }

        title
      }
    }
  }
}
