fragment GetHomeBanner on ComponentComponentsHomeBanner {
  bannerContent {
    ...BannerContentFragment
  }

  bannerMetrics {
    ...BannerMetricsFragment
  }

  bannerBottomBlocks {
    ...BannerBottomFragment
  }
}
