fragment GetHomePartners on ComponentSectionsPartners {
  title
  description

  icons(pagination: { limit: 25 }) {
    data {
      id

      attributes {
        ...MediaFragment
      }
    }
  }
}
