fragment BannerFragment on Banner {
  title
  description
  label
  imgDesktop {
    data {
      attributes {
        ...MediaFragment
      }
    }
  }
  imgMobile {
    data {
      attributes {
        ...MediaFragment
      }
    }
  }

  button {
    href
    name
  }

  widthTitle
  widthDescription
  widthDescriptionBannerOfferPage

  widthBlur
  widthBlurMobile

  offerBannerMobile {
    data {
      attributes {
        ...MediaFragment
      }
    }
  }

  offerBannerDesktop {
    data {
      attributes {
        ...MediaFragment
      }
    }
  }
}
