fragment OffersBlock on ComponentComponentsOfferComponent {
  id
  name

  offers {
    data {
      id
      attributes {
        name

        service_name {
          data {
            id

            attributes {
              name
            }
          }
        }

        description

        img {
          data {
            attributes {
              ...MediaFragment
            }
          }
        }

        sliderCase {
          ...SliderFragment
        }

        textBlocks {
          ...TextBlocksFragment
        }

        includes_blocks {
          data {
            id
            attributes {
              title

              blockHover {
                id
                title
                text
                subTitle
                list
              }

              includesContent {
                id
                title
                content
              }
            }
          }
        }
        highlighted

        offerBanner {
          data {
            attributes {
              ...BannerFragment
            }
          }
        }

        footer {
          ...FooterFragment
        }
      }
    }
  }
}
