fragment PageOffersFragment on OffersPage {
  title

  description

  img {
    data {
      attributes {
        ...MediaFragment
      }
    }
  }

  banner {
    data {
      attributes {
        ...MediaFragment
      }
    }
  }

  footer {
    ...FooterFragment
  }

  offers {
    data {
      id
      attributes {
        name

        offer {
          ...OffersFragment
        }
      }
    }
  }
}
